# Generated by Django 5.1.7 on 2025-04-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
